# Generated by Django 2.0.3 on 2018-03-29 07:19

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180328_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=models.ImageField(default='uimeis_main.jpg', storage=system.storage.ImageStorage(), upload_to='upload/%Y/%m/%d'),
        ),
    ]
